AllCops:
  TargetRubyVersion: 2.4

Rails:
  Enabled: true

#Metrics/AbcSize:
#  Exclude:
#    - apps/*/graphql/**/*.rb

Metrics/BlockLength:
  Exclude:
    - apps/*/application.rb

#Metrics/MethodLength:
#  Max: 30

Style/AndOr:
  Enabled: false

Metrics/LineLength:
  Max: 110

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Lambda:
  Exclude:
    - lib/*/graphql/**/*.rb

Style/GlobalVars:
  Enabled: false

#Style/LambdaCall:
#  Enabled: false

#Style/FrozenStringLiteralComment:
#  Enabled: false

#Style/BlockDelimiters:
#  Exclude:
#    - spec/**/*_spec.rb
#
#Lint/AmbiguousBlockAssociation:
#  Exclude:
#    - spec/**/*_spec.rb


